steps:
  - label: ':docker: Build Android base image'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.3.0:
          build:
            - android-common
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest
      - docker-compose#v3.3.0:
          push:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest

  - wait

  - label: ':docker: Build Android base CI image (using NDK r16b)'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.3.0:
          build:
            - android-ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-${BRANCH_NAME}
      - docker-compose#v3.3.0:
          push:
            - android-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-${BRANCH_NAME}

  - label: ':docker: Build Android maze runner image'
    timeout_in_minutes: 20
    plugins:
      - docker-compose#v3.3.0:
          build: android-maze-runner

  - wait

#  - label: ':docker: Build Android JVM test image'
#    timeout_in_minutes: 10
#    plugins:
#      - docker-compose#v3.3.0:
#          build: android-jvm
#          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
#          cache-from:
#            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-jvm-${BRANCH_NAME}
#      - docker-compose#v3.3.0:
#          push:
#            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-jvm-${BRANCH_NAME}

  - label: ':android: Build fixture APK'
    timeout_in_minutes: 30
    artifact_paths: build/fixture.apk
    plugins:
      - docker-compose#v3.3.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"

  - wait

  # End-to-end tests take the longest to run, so start as soon as possible.

  - label: ':android: Android 5 end-to-end tests'
    skip: Temporarily disabled due to flakiness with BrowserStack tunneling
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_5_0"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 6 end-to-end tests'
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_6_0"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 end-to-end tests'
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_7_1"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8.1 end-to-end tests'
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_8_1"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 10
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 9 end-to-end tests'
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_9_0"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 10 end-to-end tests'
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_10_0"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 10
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 11 end-to-end tests'
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v3.3.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_11_0"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 10
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"
